name: 'CI/CD'
on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  lint_js:
    name: Lint JavaScript Files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install JSHint
        run: npm install jshint --global
      - name: Run Linter
        run: |
          # Add the esversion rule to allow ES8+ syntax
          find ./giftlink-backend -name '*.js' -exec sed -i '1s;^;/*jshint esversion: 8 */\n;' {} +
          find ./giftlink-backend -name '*.js' -exec jshint {} +
          echo "Linted all JS files successfully"

  client_build:
    name: Build client
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: |
          cd giftlink-frontend
          npm ci
      - name: Build frontend
        run: |
          cd giftlink-frontend
          npm run build
          echo "Client-side build completed successfully"
